#+ summary: Get counts for biolink categories
#+ description: Get counts for biolink categories
#+ endpoint: http://kg-hub-rdf.berkeleybop.io/blazegraph/sparql

SELECT (COUNT(?v2) AS ?v1) ?v0
WHERE {
  ?v2 <https://w3id.org/biolink/vocab/category> ?v0
} GROUP BY ?v0
